model:
  embed_dim: 512           # final embedding dimension D
  part_embed_dim: 256      # per-part backbone output dim
  backbone: aagcn          # aagcn | stgcn
  fusion: attention        # concat_mlp | attention
  parts: [body, face, left_hand, right_hand, fullbody]
  drop_conf: true          # drop confidence during training/inference
