train:
  seed: 3407
  epochs: 20 # 建议增加训练轮数，确保对比学习收敛
  log_logits: false
  log_interval: 1000
  val_interval: 400
  save_dir_root: runs/robust
  save_every: 1000
  resume_from: ''

dataset:
  data_dir: /2023234331/data/shm/format_data/csl_shm
  seed: 3407
  # --- 关键改动：开启并加强数据增强 ---
  augmentations: 'speed,mask'
  aug_prob: 0.5
  aug_speed_min: 0.8
  aug_speed_max: 1.2
  aug_mask_prob: 0.15
  pad_last: true
  min_reserved_ratio: 1.0
  window: 60
  stride: 20

data:
  batch_size: 4
  num_workers: 4
  conf_threshold: 0.1
  T: 32
  train_length: 256
  val_length: 128

model:
  parts:
  - body
  - face
  - left_hand
  - right_hand
  - fullbody
  drop_conf: true
  part_embed_dim: 256
  tokens_per_chunk: 16
  uni_gcn:
    proj_dim: 256
    temporal_kernel: 7
    adaptive: true
    dropout: 0.1 # 略微增加GCN的dropout
  chunk_transformer:
    layers: 5
    heads: 8
    dropout: 0.2 # 增加Transformer的dropout
    mlp_dim: 512

llm:
  model_name_or_path: /workspace/Qwen
  trust_remote_code: true
  max_text_len: 128
  freeze_lm: true # 核心：此阶段只训练视觉部分
  gradient_checkpointing: false
  boc_token: <BOC>
  eoc_token: <EOC>
  bot_token: <BOT>
  eot_token: <EOT>
  contrastive_tau: 0.07
  contrastive_neg_k: 128
  # --- 关键改动：同时使用对比损失和多样性损失 ---
  contrastive_alpha: 1.0 # 强化对比损失，使其成为主要驱动力
  diversity_alpha: 0.5   # 引入多样性损失，对抗坍塌

decoding:
  max_new_tokens: 64
  do_sample: true
  temperature: 0.3
  top_k: 10
