train:
  seed: 3407
  epochs: 15 # 建议增加训练轮数，确保对比学习收敛
  log_logits: false
  log_interval: 25000
  val_interval: 25000
  save_dir_root: runs
  save_every: 25000
  resume_from: ''
  visual_lr: 1e-5 # 略微降低学习率，稳定训练
  llm_lr: 0.0 # LLM冻结，不更新

dataset:
  data_dirs: /2023234331/data/csl_news
  have_sub_dirs: true
  seed: 3407
  # --- 关键改动：开启并加强数据增强 ---
  augmentations: 'speed,mask'
  aug_prob: 0.5
  aug_speed_min: 0.8
  aug_speed_max: 1.2
  aug_mask_prob: 0.15
  pad_last: true
  min_reserved_ratio: 1.0
  window: 45
  stride: 30

data:
  batch_size: 8
  num_workers: 4
  conf_threshold: 0.1
  T: 32
  train_length: 256
  val_length: 128

model:
  parts:
  - body
  - face
  - left_hand
  - right_hand
  - fullbody
  drop_conf: true
  part_embed_dim: 256
  tokens_per_chunk: 12
  uni_gcn:
    proj_dim: 256
    temporal_kernel: 7
    adaptive: true
    dropout: 0.1 # 略微增加GCN的dropout
  chunk_transformer:
    layers: 5
    heads: 8
    dropout: 0.15 # 增加Transformer的dropout
    mlp_dim: 512

llm:
  model_name_or_path: /workspace/Qwen
  trust_remote_code: true
  max_text_len: 128
  freeze_lm: true # 核心：此阶段只训练视觉部分
  gradient_checkpointing: false
  boc_token: <BOC>
  eoc_token: <EOC>
  bot_token: <BOT>
  eot_token: <EOT>
  contrastive_tau: 0.08
  contrastive_neg_k: 256
  contrastive_projection_dim: 256 # Dimension of the contrastive projection head
  # --- 关键改动：同时使用对比损失和多样性损失 ---
  contrastive_alpha: 2.5 # 强化对比损失，使其成为主要驱动力
  diversity_alpha: 0.5   # 引入多样性损失，对抗坍塌

decoding:
  max_new_tokens: 64
  do_sample: true
  temperature: 0.3
  top_k: 15
