train:
  seed: 3407
  epochs: 200
  log_interval: 10
  val_interval: 2000
  save_dir_root: runs
  save_every: 400
  resume_from: ""

dataset:
  data_dir: /workspace/shm_overfit
  seed: 3407
  augmentations: ""
  aug_prob: 0.0
  aug_speed_min: 0.9
  aug_speed_max: 1.1
  aug_mask_prob: 0.05
  pad_last: true
  min_reserved_ratio: 0.6
  window: 32
  stride: 16

data:
  batch_size: 2
  num_workers: 0
  conf_threshold: 0.1
  T: 32
  train_length: 256
  val_length: 128

model:
  parts: ["body", "face", "left_hand", "right_hand", "fullbody"]
  drop_conf: true
  part_embed_dim: 256
  tokens_per_chunk: 10
  uni_gcn:
    proj_dim: 256
    temporal_kernel: 5
    adaptive: true
    dropout: 0.0
  chunk_transformer:
    layers: 2
    heads: 4
    dropout: 0.1
    mlp_dim: 512

llm:
  model_name_or_path: /workspace/Qwen
  trust_remote_code: true
  max_text_len: 128
  freeze_lm: false
  gradient_checkpointing: false
  boc_token: "<BOC>"
  eoc_token: "<EOC>"
  bot_token: "<BOT>"
  eot_token: "<EOT>"

decoding:
  max_new_tokens: 48
  do_sample: true
  temperature: 1.0
  top_k: 0

nclass: 10
